### ISSUE TITLE
Fails with the new namespace https://dev.azure.com/[AccountName]

### ISSUE THREAD

**Issue by wyzerd** [microsoft/process-migrator#40] opened 2019-11-13 19:09 UTC
I have attempted to use this with the new namespace https://dev.azure.com/[Account] on legacy orgs and it fails with bad pat until I change it to https://[Account].visualstudio.com

On the new accounts, ones that auto-forward to https://dev.azure.com, it doesn't work at all.

**Comment by z2z** [comment] 2020-02-06 07:16
@liang2zhu1 

Confirmed this failing for new projects too.

**Comment by ipindersingh** [comment] 2020-06-09 05:02
This is working now. The code seems to be usign this package: https://github.com/microsoft/azure-devops-node-api to establish the connection to the accounts. This has been updated to use the latest links which are dev.azure.com/organization. 

Hence this tool is also now working with the latest URLs. So we can close this issue.

**Comment by AminTi** [comment] 2023-07-13 12:02
We will release an update addressing previous problems. For new issues, create a ticket, and we'll resolve it promptly. Thank you for you.

**Closed by AminTi** 2023-07-13 12:02 UTC
