### ISSUE TITLE
VS403113: A group with label 'System Info' already exists in page 'Details'. 

### ISSUE THREAD

**Issue by MrHinsh** [microsoft/process-migrator#24] opened 2018-09-26 09:48 UTC
Why would I get this error in a migration of a process?

The process in the target did not exist before running this.

```
2018-09-26T09:45:11.4815277Z [VERBOSE] [2018-09-26T09:45:11.264Z] Exception message:VS403113: A group with label 'System Info' already exists in page 'Details'.
2018-09-26T09:45:11.4816018Z Call stack:Error: VS403113: A group with label 'System Info' already exists in page 'Details'.
2018-09-26T09:45:11.4817168Z     at RestClient.<anonymous> (C:\npm\prefix\node_modules\process-migrator\node_modules\typed-rest-client\RestClient.js:173:28)
2018-09-26T09:45:11.4818244Z     at Generator.next (<anonymous>)
2018-09-26T09:45:11.4819565Z     at fulfilled (C:\npm\prefix\node_modules\process-migrator\node_modules\typed-rest-client\RestClient.js:6:58)
2018-09-26T09:45:11.4821054Z     at <anonymous>
2018-09-26T09:45:11.4822460Z     at process._tickCallback (internal/process/next_tick.js:188:7)
2018-09-26T09:45:11.4823552Z [ERROR] [2018-09-26T09:45:11.264Z] Import failed, see log file for details. Failed to edit group 'Agile.Bug.Bug.System Info.WideGroup' in page 'Agile.Bug.Bug', see logs for details.
2018-09-26T09:45:11.6227377Z ##[error]Process-Migrator FAILED: Call stack:Error: VS403113: A group with label 'System Info' already exists in page 'Details'. [ERROR] [2018-09-26T09:45:11.264Z] Import failed, see log file for details. Failed to edit group 'Agile.Bug.Bug.System Info.WideGroup' in page 'Agile.Bug.Bug', see logs for details.
```

**Comment by liang2zhu1** [comment] 2018-09-27 01:41
@MrHinsh  can you send me (liangzhu at microsoft dot com) the exported process? It smells like some edge case was not captured, this is a group existing already from default template and if we don't detect change it should not try to create it on the target organization - the exception is you changed the group name under inherited process.

**Comment by MrHinsh** [comment] 2018-09-27 06:07
I can... Its a XML process that was converted to Inherited so I guess its going to come up more as that conversion has GA.

**Comment by liang2zhu1** [comment] 2018-09-28 02:14
@MrHinsh  So I understand the cause now but I'll need explore where the fix lands, it's an interesting issue. The best I can tell, and correct me if you don't think so , it must be someone renamed the group name but changed it back to the default name 'System Info'. In the exported json I see 'overrriden' is true for the group while it should be 'false' unless there's a naming change (that's pretty much the only change you can do on a group inherited from base work item type). 
I can handle this in the tool but I'm going to dig deeper first if we should make this fixed in Azure DevOps to correctly mark the overriden state.
```json
{
                    "id": "Agile.Bug.Bug.System Info.WideGroup",
                    "inherited": true,
                    "overridden": true,
                    "label": "System Info",
                    "isContribution": false,
                    "visible": true,
                    "controls": [
                      {
                        "id": "Microsoft.VSTS.TCM.SystemInfo",
                        "inherited": true,
                        "overridden": true,
                        "label": "System Info",
                        "controlType": "HtmlFieldControl",
                        "readOnly": false,
                        "watermark": "",
                        "metadata": "",
                        "visible": true,
                        "isContribution": false
                      }
                    ]
                  },
```

**Comment by MrHinsh** [comment] 2018-09-28 07:15
I don't believe that anyone has ever renamed it. This Inherited process was generated from an XML Process.

**Comment by Gizmo0815** [comment] 2019-06-14 21:59
I'm running into the same error and my exported Bug looks the same:

```
 {
                    "id": "Agile.Bug.Bug.System Info.WideGroup",
                    "inherited": true,
                    "overridden": true,
                    "label": "System Info",
                    "isContribution": false,
                    "visible": true,
                    "controls": [
                      {
                        "id": "Microsoft.VSTS.TCM.SystemInfo",
                        "inherited": true,
                        "overridden": true,
                        "label": "System Info",
                        "controlType": "HtmlFieldControl",
                        "readOnly": false,
                        "watermark": "",
                        "metadata": "",
                        "visible": true,
                        "isContribution": false
                      }
                    ]
                  }
```

**Comment by Gizmo0815** [comment] 2019-06-14 22:15
I just figured it out: It seems the bugs "System Info" field has really been modified. By clicking the context menu of "System Info" in the bug layout and selecting "Revert" I was able to set it back to it's original state and the error did no longer occure during migration.

**Closed** 2019-07-12 21:17 UTC
